import { MD3LightTheme as DefaultTheme } from 'react-native-paper';

export const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: '#6366f1',
    primaryContainer: '#e0e7ff',
    secondary: '#8b5cf6',
    secondaryContainer: '#f3e8ff',
    tertiary: '#06b6d4',
    tertiaryContainer: '#cffafe',
    surface: '#ffffff',
    surfaceVariant: '#f1f5f9',
    background: '#fafbfc',
    error: '#ef4444',
    errorContainer: '#fef2f2',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#312e81',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#581c87',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#0c4a6e',
    onSurface: '#1e293b',
    onSurfaceVariant: '#475569',
    onError: '#ffffff',
    onErrorContainer: '#7f1d1d',
    onBackground: '#1e293b',
    outline: '#94a3b8',
    outlineVariant: '#cbd5e1',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#334155',
    inverseOnSurface: '#f1f5f9',
    inversePrimary: '#a5b4fc',
    elevation: {
      level0: 'transparent',
      level1: '#ffffff',
      level2: '#f8fafc',
      level3: '#f1f5f9',
      level4: '#e2e8f0',
      level5: '#cbd5e1',
    },
  },
  roundness: 12,
};